### ISSUE TITLE
Example code for fine-grained recognition

### ISSUE THREAD

**Issue by zhj1ein** [ahmdtaha/softmax_triplet_loss#1]
Thanks for your code! 
Could you please point out the batch construction methods used in your code? And may I ask if you have a chance to provide one example code on fine-grained recognition data so that I can understand your work in depth?

Thanks again.
Jun

**Comment by ahmdtaha** [comment]
The batch construction method, for semi-triplet loss, is encapsulated inside the [TripletTupleLoader](https://github.com/ahmdtaha/softmax_triplet_loss/blob/0a94f23f8ba378c0142a294f181b41f5f1930d90/fast_fgvr_semi_train.py#L69)

This class takes a list of images' filepaths, images' labels and experiment configuration.
The main configuration needed by this class is the mini_batch size and number of samples per class (base_config->Triplet_K). For example, if mini_batch size = 32 and Triplet_K=4, the constructed mini_batch will have 32 sample, 8 different classes and 4 samples per class (4x8=32).

I will update the readme file with an example run command and update this issue accordingly.

**Comment by ahmdtaha** [comment]
@pencilzhang , I updated the `usage example` section in the readme file. I hope this helps using the code. Let me know if you have further questions

**Comment by zhj1ein** [comment]
Thank you Ahmed! I have tested the code and it works well.
